pre commit files updated

diff --git a/bin/git_hooks/pre-commit b/bin/git_hooks/pre-commit
--- a/bin/git_hooks/pre-commit
+++ b/bin/git_hooks/pre-commit
@@ -10,23 +10,27 @@ printf "\n==================== Frontend code-style checks ====================\n
 # Frontend linting
 #-------------------------------------------------------------------------------
 
-if [[ $(git diff --name-only HEAD@{1} HEAD | grep -E 'frontend/.*\.(js|ts|vue)$') ]]; then
-  # variable for all changed files
-  changed_files=$(git diff --name-only HEAD@{1} HEAD | grep -E 'frontend/.*\.(js|ts|vue)$')
+# Get list of staged files that match the frontend file pattern
+staged_files=$(git diff --cached --name-only --diff-filter=d | grep -E 'frontend/.*\.(js|ts|vue)$')
 
-  # Run linting command
-  for file in $changed_files; do
-    # We need to remove src/frontend/ from the start of the file path
-    files_to_format="${files_to_format} ${file#src/frontend/}"
-    echo "✏️ ${files_to_format}"
-  done
+if [[ $staged_files ]]; then
+  echo "Files to format and lint:"
+  echo "$staged_files"
 
-  cd src/frontend && npm run format-specific -- ${files_to_format} && npm run lint-specific -- ${files_to_format}
+  # Run formatting and linting commands on staged files
+  npm run format-specific -- $staged_files
+  format_status=$?
 
-  if [ $? -ne 0 ]; then
-      echo "${red} ❌ Failed frontend linting ${color_off}\n"
-      exit 1
+  npm run lint-specific -- $staged_files
+  lint_status=$?
+
+  git add $staged_files
+
+  # If either formatting or linting failed, exit with an error
+  if [[ $format_status -ne 0 || $lint_status -ne 0 ]]; then
+    echo "${red}❌ Frontend code-style checks failed${color_off}\n"
+    exit 1
   else
-      echo "${green} ✅ Passed frontend linting ${color_off}\n"
+    echo "${green}✅ Frontend code-style checks passed${color_off}\n"
   fi
 fi
